server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: jpaTraining
  datasource:
    initialization-mode: never
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:jpa}
    username: ${POSTGRES_USER:jpa}
    password: ${POSTGRES_PASSWORD:jpa}
    maxActive: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true